# Generated by Django 2.0.1 on 2018-04-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
