# Generated by Django 2.0.1 on 2018-01-21 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='supercategory',
            options={'verbose_name_plural': 'super categories'},
        ),
    ]
