# Generated by Django 2.0.1 on 2018-02-10 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180210_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(help_text='URL name: <em>thunderatz.org/projects/&lt;slug&gt;</em>', unique=True),
        ),
    ]
