# Generated by Django 2.0.1 on 2018-01-21 20:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180121_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
