# Generated by Django 2.0.1 on 2018-04-16 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("projects", "0003_project_card_and_top")]

    operations = [migrations.RemoveField(model_name="project", name="thumbnail")]
