# Generated by Django 2.0.1 on 2018-04-16 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0005_remove_project_card_and_top")]

    operations = [
        migrations.AddField(
            model_name="project",
            name="card_and_top",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="thumbnail",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
