# Generated by Django 2.0.1 on 2018-01-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_situation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='situation',
        ),
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
