# Generated by Django 2.0.1 on 2018-02-23 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20180222_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='robots',
        ),
        migrations.AddField(
            model_name='project',
            name='boards',
            field=models.ManyToManyField(to='projects.Board'),
        ),
    ]
