# Generated by Django 2.0.1 on 2018-01-22 18:54

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20180122_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(default='', upload_to=projects.models.project_image_path),
            preserve_default=False,
        ),
    ]
