# Generated by Django 2.0.1 on 2018-02-23 03:56

from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20180222_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=projects.models.board_images_path)),
                ('description', models.CharField(max_length=512)),
            ],
        ),
        migrations.AlterField(
            model_name='board',
            name='thumbnail',
            field=models.ImageField(upload_to=projects.models.board_thumbnail_path),
        ),
        migrations.AddField(
            model_name='boardimage',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='projects.Board'),
        ),
    ]
