# Generated by Django 2.0.1 on 2018-04-16 23:29

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [("projects", "0007_auto_20180416_2027")]

    operations = [
        migrations.AddField(
            model_name="project",
            name="card_image",
            field=models.ImageField(
                default="", upload_to=projects.models.project_card_path
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="cover_image",
            field=models.ImageField(
                default="", upload_to=projects.models.project_cover_path
            ),
            preserve_default=False,
        ),
    ]
