# Generated by Django 2.0.1 on 2018-04-17 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0009_auto_20180416_2140")]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="project_logos"),
        )
    ]
