# Generated by Django 2.0.1 on 2018-03-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20180305_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='boards',
            field=models.ManyToManyField(blank=True, to='projects.Board'),
        ),
    ]
