# Generated by Django 2.0.1 on 2018-03-17 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20180305_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-is_active', 'name']},
        ),
    ]
