# Generated by Django 2.0.1 on 2018-04-19 01:31

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [("projects", "0011_auto_20180416_2226")]

    operations = [
        migrations.RemoveField(model_name="board", name="thumbnail"),
        migrations.AddField(
            model_name="board",
            name="card_image",
            field=models.ImageField(
                default="1000x1000.png", upload_to=projects.models.board_card_path
            ),
        ),
        migrations.AddField(
            model_name="board",
            name="cover_image",
            field=models.ImageField(
                default="1000x1000.png", upload_to=projects.models.board_cover_path
            ),
        ),
    ]
