# Generated by Django 2.0.1 on 2018-03-18 15:32

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20180316_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='card_and_top',
            field=models.ImageField(default='http://via.placeholder.com/1920x1080', upload_to=projects.models.project_card_path),
            preserve_default=False,
        ),
    ]
