# Generated by Django 2.0.1 on 2018-05-29 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20180528_2149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['name']},
        ),
    ]
