# Generated by Django 2.0.1 on 2018-02-10 03:57

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import news.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('text', ckeditor.fields.RichTextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('visible', models.BooleanField(default=False)),
                ('cover_image', models.ImageField(upload_to='news_cover')),
                ('author', models.ForeignKey(on_delete=models.SET(news.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'news',
            },
        ),
    ]
