# Generated by Django 2.0.1 on 2018-02-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(help_text='URL name: <em>thunderatz.org/news/&lt;slug&gt;</em>', unique=True),
        ),
    ]
