# Generated by Django 2.0.8 on 2020-02-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180528_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='intro_on_text',
            field=models.BooleanField(default=False),
        ),
    ]
