# Generated by Django 2.0.8 on 2020-02-01 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_intro_on_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='intro_on_text',
            new_name='cover_on_text',
        ),
    ]
