# Generated by Django 2.0.8 on 2020-02-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200201_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='cover_on_text',
        ),
        migrations.AddField(
            model_name='news',
            name='cover_on_text_end',
            field=models.BooleanField(default=False, help_text='Define se a imagem de capa aparece no final da notícia.'),
        ),
    ]
