# Generated by Django 2.0.8 on 2020-08-18 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200201_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='cover_on_text_end',
            field=models.BooleanField(default=True, help_text='Define se a imagem de capa aparece no final da notícia.'),
        ),
    ]
