# Generated by Django 2.0.1 on 2018-03-18 16:33

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20180311_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='<strong>Se upar imagens, colocar a classe "body-image" nela!</strong>'),
        ),
    ]
