# Generated by Django 2.0.1 on 2018-01-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('website', models.URLField(unique=True)),
                ('quota', models.CharField(choices=[('O', 'Ouro'), ('P', 'Prata'), ('B', 'Bronze'), ('A', 'Apoio')], max_length=1)),
            ],
        ),
    ]
