# Generated by Django 2.0.1 on 2018-01-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(default='', upload_to='sponsors'),
            preserve_default=False,
        ),
    ]
