# Generated by Django 2.0.8 on 2019-02-02 18:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('text', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='ps')),
                ('isOpen', models.BooleanField(default=False)),
                ('info', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
