# Generated by Django 2.0.1 on 2018-01-18 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_sponsor_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='quota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Quota'),
        ),
    ]
