# Generated by Django 2.0.8 on 2019-02-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_recruitment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='isOpen',
            field=models.BooleanField(default=True),
        ),
    ]
