# Generated by Django 2.0.8 on 2019-02-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20190202_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='isOpen',
            field=models.BooleanField(default=False),
        ),
    ]
