# Generated by Django 2.0.1 on 2018-01-29 01:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20180121_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('text', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
