# Generated by Django 2.0.8 on 2019-02-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_auto_20190203_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='button',
            field=models.TextField(default='', help_text='Cole o script do Typeform aqui'),
        ),
    ]
