# Generated by Django 2.0.1 on 2018-01-29 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='events'),
        ),
    ]
