# Generated by Django 2.0.8 on 2019-02-15 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_recruitment_button'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitment',
            name='text',
        ),
    ]
