# Generated by Django 2.0.8 on 2022-01-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_remove_recruitment_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('current_value', models.IntegerField()),
                ('maximum_value', models.IntegerField()),
            ],
        ),
    ]
