# Generated by Django 2.0.8 on 2022-10-25 02:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_progressbar'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressbar',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progressbar',
            name='pix_link',
            field=models.URLField(default=''),
        ),
    ]
