# Generated by Django 2.0.1 on 2018-03-03 17:57

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['team_captain', 'area_captain', 'name']},
        ),
        migrations.AddField(
            model_name='member',
            name='area',
            field=models.CharField(choices=[('EL', 'Elétrica'), ('MC', 'Mecânica'), ('CP', 'Computação'), ('DM', 'Design e Marketing'), ('AF', 'Administrativo e Financeiro')], default='EL', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='area_captain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='picture',
            field=models.ImageField(default='', upload_to=members.models.member_picture_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='team_captain',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='nickname',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
