# Generated by Django 2.0.1 on 2018-04-19 01:58

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='picture',
            field=models.ImageField(default='1000x1000.png', upload_to=members.models.member_picture_path),
        ),
    ]
