# Generated by Django 2.0.1 on 2018-03-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20180303_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
    ]
