# Generated by Django 2.0.1 on 2018-03-03 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_facebook'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-team_captain', '-area_captain', 'name']},
        ),
    ]
