# Generated by Django 2.0.1 on 2018-03-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20180303_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(default='teste@teste.org', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='entry_year',
            field=models.PositiveSmallIntegerField(default=2016),
            preserve_default=False,
        ),
    ]
